// Generated by CoffeeScript 1.7.1
var assert;

assert = chai.assert;

describe('deck', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    return deck = new Deck();
  });
  return describe('hit', function() {
    return it("fill this in with a test", function() {});
  });
});
